version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./etc/db:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: naGeEcsztjVn1nDs
      MYSQL_DATABASE: ticket_system
      MYSQL_USER: ticket_system
      MYSQL_PASSWORD: naGeEcsztjVn1nDs
    ports:
      - 3306:3306
  api:
    build: .
    image: php:7.2-apache
    depends_on:
      - db
    ports:
      - ${PORT}:80
    labels: 
      - "traefik.http.routers.real-state-admin-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.real-state-admin-api.entrypoints=websecure"
      - "traefik.http.routers.real-state-admin-api.tls.certresolver=myresolver"
      - "traefik.http.services.real-state-admin-api.loadbalancer.server.port=${PORT}"
    networks:
      - traefik-network

volumes:
  mysqldata:

networks:
  traefik-network:
    external:
      name: traefik_proxynet